$ANSIBLE_VAULT;1.1;AES256
38316566613966613438613632363666323833336634363034623433643365356564643161653535
6433353237313231373064646432613439653562636333660a653139336165396339393134663637
32353461326539333062376163396539666635343731393161323230333761333339373738633761
6233306331633333300a663339343037303961303535366534383966346139663761346630306336
62303362666232373862353765653032356136303430303332376662383761663465653037326634
64323432343763643732643932626361616535643338303031623738333764633763333234326363
39373234373435386139626237633937623462373430616462323137623130623938333134623531
64663535303536623261366630653537333964373835343139393933616161393166313366363131
38616236623664306262323135633761383035363262366338386261633664346530623637613437
31313430666631386135343964336331323633386132363865643361653964613965656333303932
353634303537306662366261363333383031
